version: '3'

services:

  #DB

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=C@$eP1sm0
      - MYSQL_DATABASE=casepismo
    expose:
      - 3306

    networks:
      - backend


  #Api
  springboot:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/casepismo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: C@$eP1sm0
    image: pismocontainer:latest
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql
networks:
  backend:
