version: '3'

services:

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=M@g1st3r10
      - MYSQL_DATABASE=casepismo
    expose:
      - 3306
    volumes:
      - "/usr/local/mysql/data:/var/lib/mysql/data"
    networks:
      - backend
  springboot:
    build:
      context: ./
      dockerfile: Dockerfile
    image: pismocontainer:latest
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
networks:
  backend:
