version: '2.1'

services:

  #DB

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=C@$eP1sm0
      - MYSQL_DATABASE=casepismo
    expose:
      - 3306

    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


  #Api
  springboot:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/casepismo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: C@$eP1sm0
    image: pismocontainer:latest
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

    links:
      - mysql
networks:
  backend:
